export const
  //pagination
  CHANGE_PAGE = 'CHANGE_PAGE',
  CHANGE_AVAILABLE_PAGES = 'CHANGE_AVAILABLE_PAGES',
  //request
  REQUEST_SEND = 'REQUEST_SEND',
  REQUEST_RECEIVED = 'REQUEST_RECEIVED',
  REQUEST_ERROR = 'REQUEST_ERROR',
  // views
  CHANGE_CONTENT = 'CHANGE_CONTENT',
  CHANGE_VIEW = 'CHANGE_VIEW',
  UPDATE_ROW = 'UPDATE_ROW',
  // search
  CHANGE_SEARCH_BY = 'CHANGE_SEARCH_BY',
  CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT',
  CHANGE_SEARCH_DATA = 'CHANGE_SEARCH_DATA';

